### ISSUE TITLE
Functions To Change the CASE?

### ISSUE THREAD

**Issue by courtiol** [hadley/stringb#4]
It would be great to have equivalents for the following stringr functions:
- `str_to_upper(string, locale = "en")`
- `str_to_lower(string, locale = "en")`
- `str_to_title(string, locale = "en")`
- `str_to_sentence(string, locale = "en")`

For the first two, there are base alternatives (`tolower(x)` & `toupper(x)`), but AFAIK nothing direct for the last two.

**Comment by hadley** [comment]
This is unfortunately out of scope since title and sentence case require a large set of heuristics.
